name = "ircbot"
version = "0.1.0"
licences = ["GPL-3.0"]
description = "A Gleam ircbot"
repository = { type = "github", user = "gdamjan", repo = "ircbot-gleam" }
gleam = ">= 1.5.0"
target = "erlang" # Erlang/OTP >= 27

[dependencies]
gleam_stdlib = ">= 0.40.0 and < 1.0.0"
gleam_erlang = ">= 0.26.0 and < 1.0.0"
gleam_gun = { path = "vendor/gleam_gun" }
certifi = ">= 2.13.0 and < 3.0.0"
gleam_http = ">= 3.7.0 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.2.0 and < 2.0.0"
