name = "ircbot"
version = "0.1.0"
licences = ["GPL-3.0"]
description = "A Gleam ircbot"
repository = { type = "github", user = "gdamjan", repo = "ircbot-gleam" }
gleam = ">= 1.7.0"
target = "erlang" # Erlang/OTP >= 27

[dependencies]
gleam_stdlib = ">= 0.52.0 and < 1.0.0"
gleam_erlang = ">= 0.33.0 and < 1.0.0"
gleam_http = ">= 3.7.2 and < 4.0.0"
gleam_json = ">= 2.3.0 and < 3.0.0"
gleam_httpc = ">= 4.0.0 and < 5.0.0"
birl = ">= 1.8.0 and < 2.0.0"
envoy = ">= 1.0.2 and < 2.0.0"
[dev-dependencies]
gleeunit = ">= 1.2.0 and < 2.0.0"
