name = "ircbot"
version = "0.1.0"
licences = ["GPL-2.0"]
description = "A Gleam ircbot"
repository = { type = "github", user = "gdamjan", repo = "ircbot-gleam" }

[dependencies]
gleam_stdlib = "~> 0.19"
gleam_otp = "~> 0.3"
gleam_erlang = "~> 0.8"

[dev-dependencies]
gleeunit = "~> 0.6"
