name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26"
          gleam-version: "1.4"
          rebar3-version: "3"

      - run: gleam format --check src test
      - run: gleam deps download
      - run: gleam test

      - name: Create artifact
        run: gleam export erlang-shipment

      - uses: actions/upload-artifact@v4
        with:
          name: erlang-shipment
          path: build/erlang-shipment/
