name: Make a release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    env:
      RELEASE_ARTIFACT: release-${{ github.ref_name }}.tar.gz
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27"
          gleam-version: "1.7"

      - name: Create artifact
        run: |
          gleam export erlang-shipment
          tar -C build/erlang-shipment/ -caf $RELEASE_ARTIFACT .

      - name: Attest build provenance
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: ${{ env.RELEASE_ARTIFACT }}

      - name: Upload artifacts to github-releases
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.RELEASE_ARTIFACT }}*
          file_glob: true
          tag: ${{ github.ref }}
